allowBuilds:
  '@keqingmoe/tree-sitter': true
  '@tree-sitter-grammars/tree-sitter-lua': true
  better-sqlite3: true
  esbuild: true
  tree-sitter-bash: true
  tree-sitter-c: true
  tree-sitter-c-sharp: true
  tree-sitter-cli: false
  tree-sitter-cpp: true
  tree-sitter-go: true
  tree-sitter-java: true
  tree-sitter-javascript: true
  tree-sitter-kotlin: true
  tree-sitter-lua: set this to true or false
  tree-sitter-php: true
  tree-sitter-python: true
  tree-sitter-ruby: true
  tree-sitter-rust: true
  tree-sitter-swift: true
  tree-sitter-typescript: true
